/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "1.5rem", screens: { "2xl": "1440px" } },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Menlo", "Monaco", "monospace"],
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "1.4" }],
        xs:   ["0.75rem",   { lineHeight: "1.4" }],
        sm:   ["0.8125rem", { lineHeight: "1.5" }],
        base: ["0.9375rem", { lineHeight: "1.6" }],
        lg:   ["1.0625rem", { lineHeight: "1.5" }],
        xl:   ["1.1875rem", { lineHeight: "1.4" }],
        "2xl":["1.375rem",  { lineHeight: "1.3" }],
        "3xl":["1.75rem",   { lineHeight: "1.25" }],
        "4xl":["2.25rem",   { lineHeight: "1.15" }],
      },
      colors: {
        border:       "hsl(var(--border))",
        "border-strong": "hsl(var(--border-strong))",
        input:        "hsl(var(--input))",
        ring:         "hsl(var(--ring))",
        background:   "hsl(var(--background))",
        surface:      "hsl(var(--surface))",
        "surface-raised": "hsl(var(--surface-raised))",
        foreground:   "hsl(var(--foreground))",
        "foreground-muted":  "hsl(var(--foreground-muted))",
        "foreground-subtle": "hsl(var(--foreground-subtle))",
        primary: {
          DEFAULT:    "hsl(var(--primary))",
          hover:      "hsl(var(--primary-hover))",
          foreground: "hsl(var(--primary-foreground))",
          subtle:     "hsl(var(--primary-subtle))",
          muted:      "hsl(var(--primary-muted))",
        },
        secondary: {
          DEFAULT:    "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT:    "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          subtle:     "hsl(var(--destructive-subtle))",
        },
        success: {
          DEFAULT:    "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          subtle:     "hsl(var(--success-subtle))",
        },
        warning: {
          DEFAULT:    "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          subtle:     "hsl(var(--warning-subtle))",
        },
        muted: {
          DEFAULT:    "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT:    "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT:    "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT:    "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        // Named brand scale
        navy: {
          50:  "hsl(220 60% 97%)",
          100: "hsl(220 55% 93%)",
          200: "hsl(220 50% 85%)",
          300: "hsl(220 45% 72%)",
          400: "hsl(220 42% 58%)",
          500: "hsl(220 65% 46%)",
          600: "hsl(220 70% 38%)",
          700: "hsl(220 72% 30%)",
          800: "hsl(220 74% 22%)",
          900: "hsl(220 76% 15%)",
        },
      },
      borderRadius: {
        sm: "0.3125rem",
        DEFAULT: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        xs:   "var(--shadow-xs)",
        sm:   "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        md:   "var(--shadow-md)",
        lg:   "var(--shadow-lg)",
        xl:   "var(--shadow-xl)",
        "inner-sm": "inset 0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      spacing: { 18: "4.5rem", 22: "5.5rem" },
      screens: {
        xs: "480px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1440px",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        shimmer: {
          "0%":   { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to:   { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.18s ease-out",
        "accordion-up":   "accordion-up 0.18s ease-out",
        "shimmer":        "shimmer 1.4s ease-in-out infinite",
        "fade-up":        "fade-up 0.3s ease forwards",
        "fade-in":        "fade-in 0.2s ease forwards",
        "scale-in":       "scale-in 0.2s ease forwards",
        "pulse-slow":     "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
